'use client'
import './globals.css'
import { useState } from 'react'
import { UserContext } from './utils/context/userContext'
import { useParams } from 'next/navigation'
import Landing from '@/components/landing/Landing'



//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  //status si el ususario esta log
  const [userStatus, setUserStatus] = useState()
  //useparams para la navegacion entre path dinamicos
  const params = useParams()
  return (
    <UserContext.Provider value={{ userStatus, setUserStatus }}>
      <html lang="en" className="h-full">
        <body className={'h-full min-h-screen font-sans'}>
          <div className="flex h-full min-h-screen justify-center">
            {params.routes ? (<div className="w-full">{children}</div>)
              : (
                <Landing />
              )
            }
          </div>
        </body>
      </html>
    </UserContext.Provider >

  )
};
